export const fs = { readFileSync: () => '', writeFileSync: () => {} };
export const path = { dirname: () => '', join: () => '', resolve: () => '' };
export const url = { fileURLToPath: () => '', pathToFileURL: () => '' };
export const crypto = { getRandomValues: () => new Uint8Array(16) };
export const module = {};
export const os = { platform: () => 'browser' };
export const worker_threads = {};
export const child_process = {};
export default { fs, path, url, crypto, module, os, worker_threads, child_process };
export const promises = { readFile: () => Promise.resolve(''), writeFile: () => Promise.resolve() };
export const dirname = () => '';
export const readFileSync = () => '';
export const writeFileSync = () => {};
export const join = () => '';
export const resolve = () => '';
export const fileURLToPath = () => '';
export const pathToFileURL = () => '';
export const getRandomValues = () => new Uint8Array(16);
export const platform = () => 'browser';
